config/routes.rb
Rails.application.routes.draw do

  resources :products, only: [:index]

  root to: "products#index"

  post 'populate/:product_id', to: 'orders#populate', as: 'populate'

  resources :orders, only: [:update]
  get  'order/:order_id', to: 'orders#edit', as: 'checkout'
  post 'orders/:order_id/add_address', to: 'orders#add_address', as: 'add_address'
  post 'orders/:order_id/complete', to: 'orders#complete', as: 'complete'

  post 'line_items/:line_item_id/delete', to: 'line_items#destroy'

  resources :products
  resources :sessions, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/address.rb
class Address < ApplicationRecord
  with_options presence: true do
    validates :first_name, :last_name
    validates :street, :postal_code
    validates :mobile_phone
  end

  def full_name
    "#{first_name} #{last_name}".strip if first_name && last_name
  end

  def to_s
    "#{street} #{postal_code} #{city}"
  end

  def name
    "#{self.mobile_phone} - #{self.full_name}, #{self.to_s}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product, optional: true

  monetize :total_cents

  def create_variants(prototypes)
    prototypes.each do |prototype|
      Core::Variant.create(line_item: self, prototype: prototype)
    end
  end

  def update_adjustments

  end

  def price
    product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include NumberGenerator.new(prefix: 'R')
  include TokenGenerator
  extend FriendlyId
  friendly_id :number, use: [:slugged, :finders]

  belongs_to :user, optional: true

  belongs_to :address, foreign_key: :address_id, class_name: 'Address', optional: true

  scope :created_between, -> (start_date, end_date) { where(created_at: start_date..end_date) }
  scope :completed_between, -> (start_date, end_date) { where(completed_at: start_date..end_date) }
  scope :complete, -> { where.not(completed_at: nil) }
  scope :incomplete, -> { where(completed_at: nil) }

  # shows completed orders first, by their completed_at date, then uncompleted orders by their created_at
  scope :reverse_chronological, -> { order(Arel.sql('orders.completed_at IS NULL'), completed_at: :desc, created_at: :desc) }

  has_many :line_items, :dependent => :destroy

  validates :number, presence: true, length: { maximum: 32, allow_blank: true }, uniqueness: { allow_blank: true }

  with_options presence: true do
    validates :address, if: :is_completed?
    validates :status
    validates :total, numericality: { greater_than: 0 }, if: :is_completed?
  end

  monetize :total_cents

  def self.statuses
    %w(cart processing paid delivered)
  end

  self.statuses.each do |status|
    define_method :"#{status}?" do |*args|
      self.status.eql? status
    end
  end

  def is_completed?
    self.completed_at.present?
  end

  def update_adjustments
    self.total = 0
    self.line_items.each do |li|
      self.total += li.product.price
    end
    self.save!
  end

  # Associates the specified user with the order.
   def associate_user!(user, override_email = true)
     self.user           = user
     self.save!
   end
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :sku, use: :slugged

  monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_many :orders

  def last_incomplete_order
    orders.incomplete.order('created_at DESC').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  include ControllerHelpers::OrderHelper
  protect_from_forgery

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.select(:id, :email).find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ActionController::Base
  before_action :authorize
  
  def destroy
    line_item = LineItem.find(params[:line_item_id])
    order = line_item.order

    if order && order.cart?
      if order.line_items.count == 1
        order.destroy
      else
        line_item.destroy
      end

      respond_to do |format|
        format.html { redirect_to cart_url }
        format.js   { }
      end
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authorize

  def edit
    @current_order = current_user.last_incomplete_order
  end

  def add_address
    @current_order = current_user.last_incomplete_order
    begin
      ActiveRecord::Base.transaction do
        if @current_order.address.present?
          @current_order.address.update!(address_params)
        else
          @address = Address.new(address_params)
          @current_order.address = @address if @address.save!
        end

        @current_order.save!
      end
    rescue ActiveRecord::RecordInvalid => exception
      @error_message = exception.message
    end

    respond_to do |format|
      format.js { render :edit }
    end
  end

  def populate
    if add_line_item
      respond_to do |format|
        format.js { render :populate }
      end
    end
  end

  def complete
    @current_order = current_user.last_incomplete_order
    @current_order.update!(completed_at: DateTime.now)
    OrdersMailer.complete(@current_order).deliver
    render :return
  end

  private

  def address_params
    params.require(:address).permit(:first_name, :last_name, :postal_code, :city,
                                    :street, :floor, :phone, :mobile_phone)
  end

  def line_item_params
    params.require(:line_item)
  end

  def add_line_item
    begin
      Order.transaction do
        product = Product.find(params[:product_id])
        line_item = LineItem.create!({order: current_order(create_order_if_necessary: true), product: product}) unless product.nil?
        line_item.order.update_adjustments
      end
    rescue
      return false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ControllerHelpers::OrderHelper
  before_action :authorize

  layout 'application'

  def index
    query = params[:query]
    if query.present?
      @products = Product.where("name LIKE ? or sku LIKE ?", "%#{query}%", "%#{query}%")
    else
      @products = Product.all
    end

    @order = current_order
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def concat_options(h1, h2)
    h1.merge(h2) do |_, v1, v2| 
      v1.concat(" #{v2}")
    end
  end

  def material_icon_tag(name, options = nil, html_options = nil)
    html_options = concat_options({:class => 'material-icons'}, html_options ||= {})
    html_options = convert_options_to_data_attributes(options, html_options)
    content_tag :i, options, html_options do
      name.to_s
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id='navbar'><%= render partial: 'shared/navbar' %></div>
    <main>
      <%= yield %>
    </main>
    <div id='footer'><%= render partial: 'shared/footer' %></div>
  </body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_address.html.erb
<% if @error_message %>
  <div class="row">
    <div class="col s12 m12">
      <div class="card-panel red">
        <span class="white-text"><%= @error_message %></span>
      </div>
    </div>
  </div>
<% end %>

<%= form_for @current_order.address || @address || Address.new, as: :address, url: add_address_path, method: :post, remote: true do |form| %>
  <div class="row">
    <div class="col s12 p-a-0 p-b-40 m-b-40 input-group">
      <div class="input-field col s12 m6">
        <%= form.label :first_name  %>
        <%= form.text_field :first_name %>
      </div>
      <div class="input-field col s12 m6">
        <%= form.label :last_name %>
        <%= form.text_field :last_name %>
      </div>
    </div>

    <div class="col s12 p-a-0 p-b-40 m-b-40 input-group">
      <div class="input-field col s12 m6">
        <%= form.label :postal_code  %>
        <%= form.text_field :postal_code %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :city  %>
        <%= form.text_field :city %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :street  %>
        <%= form.text_field :street %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :floor  %>
        <%= form.text_field :floor %>
      </div>
    </div>

    <div class="col s12 p-a-0 p-b-40 m-b-40 input-group">
      <div class="input-field col s12 m6">
        <%= form.label :phone  %>
        <%= form.text_field :phone %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :mobile_phone  %>
        <%= form.text_field :mobile_phone %>
      </div>
    </div>
  </div>

  <%= form.button :submit, :class => 'waves-effect waves-light btn' do %>
    <i class="material-icons md-24">send</i>
  <% end %>
<% end %>

app/views/orders/_complete.html.erb
<div class="row">
  <div class="col s12 p-a-0 p-b-40 m-b-40 input-group">
    <div class="input-field col s12 m6">
      <%= label_tag :first_name, nil, {class: 'active'} %>
      <%= text_field_tag :first_name, target.address.first_name, disabled: true %>
    </div>
    <div class="input-field col s12 m6">
      <%= label_tag :last_name, nil, {class: 'active'} %>
      <%= text_field_tag :last_name, target.address.last_name, disabled: true %>
    </div>
  </div>

  <div class="col s12 p-a-0 p-b-40 m-b-40 input-group">
    <div class="input-field col s12 m6">
      <%= label_tag :postal_code, nil, {class: 'active'} %>
      <%= text_field_tag :postal_code, target.address.postal_code, disabled: true %>
    </div>

    <div class="input-field col s12 m6">
      <%= label_tag :city, nil, {class: 'active'} %>
      <%= text_field_tag :city, target.address.city, disabled: true %>
    </div>

    <div class="input-field col s12 m6">
      <%= label_tag :street, nil, {class: 'active'} %>
      <%= text_field_tag :street, target.address.street, disabled: true %>
    </div>

    <div class="input-field col s12 m6">
      <%= label_tag :floor, nil, {class: 'active'} %>
      <%= text_field_tag :floor, target.address.floor, disabled: true %>
    </div>
  </div>

  <div class="col s12 p-a-0 p-b-40 m-b-40 input-group">
    <div class="input-field col s12 m6">
      <%= label_tag :phone, nil, {class: 'active'} %>
      <%= text_field_tag :phone, target.address.phone, disabled: true %>
    </div>

    <div class="input-field col s12 m6">
      <%= label_tag :mobile_phone, nil, {class: 'active'}  %>
      <%= text_field_tag :mobile_phone, target.address.mobile_phone, disabled: true %>
    </div>
  </div>
</div>

<%= link_to complete_path(target), :class => 'waves-effect waves-light btn', method: :post do %>
  <i class="material-icons md-24">done</i>
<% end %>

app/views/orders/edit.html.erb
<div class="row m-t-50">
  <div class="col s12 m6">
    <% if @current_order %>
      <ul class="collection">
        <% @current_order.line_items.each do |li| %>
        <li class="collection-item avatar">
          <i class="material-icons circle green">label</i>
          <span class="title"><%= li.product.name %></span>
          <p><label><%= humanized_money_with_symbol li.product.price %></label></p>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div id="address_section" class="col s12 m6">
    <%= render partial: 'address' %>
  </div>
</div>

app/views/orders/edit.js.erb
<% if @error_message %>
    document.getElementById("address_section").innerHTML = ("<%= escape_javascript(render partial: 'orders/address') %>");
<% else %>
    document.getElementById("address_section").innerHTML = ("<%= escape_javascript(render partial: 'orders/complete', locals: {target: @current_order}) %>");
<% end %>

M.updateTextFields()

app/views/orders/populate.js.erb
document.getElementById("footer").innerHTML = ("<%= escape_javascript(render partial: 'shared/footer') %>");

app/views/orders/return.html.erb
<div class="center order-completed-message">
  <h6>Your order <%= @current_order.number %> has been submitted successfully!</h6>
  <i class="material-icons md-48">check</i>
  <p>Rerurn to home</p>
  <%= link_to root_path, :class => 'waves-effect waves-light btn' do %>
    <i class="material-icons md-24">store</i>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="sign-in row m-t-50">
    <% @products.each do |product| %>
      <!-- Page content -->
      <div class="col s4">
        <div class="card small">
          <div class="card-content">
            <label class="card-title"><%= product.name %></label>
            <label><%= humanized_money_with_symbol product.price %></label>
            <!-- title -->
          </div>
          <div class="card-action">
            <%= link_to "Add to Cart", populate_path(product), method: :post, remote: true %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<br></br><br></br>
<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <% if @current_order %>
        <%= link_to checkout_path(@current_order), :class => 'waves-effect waves-light btn right' do %>
          <i class="material-icons md-24">shopping_cart</i><i class="material-icons md-24">arrow_forward</i>
        <% end if @current_order.total > 0 && action_name != 'edit' && action_name != 'complete' %>
        <span class="m-l-15"><%= I18n.t(:item, count: @current_order.line_items.count, scope: [:basic]) %> <%= humanized_money_with_symbol @current_order.total %></span>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<!-- Dropdown Structure -->
<% if current_user.present? %>
  <ul id="dropdown" class="dropdown-content">
    <li>
      <%= link_to logout_path do %>
        <%= material_icon_tag :power_settings_new %>
        <%= I18n.t(:sign_out, scope: [:devise, :sessions]) %>
      <% end %>
    </li>
  </ul>
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper teal">
        <div class="row">
          <%= form_tag '/products', method: :get, class: 'col s6' do |f| %>
            <%= button_tag nil, :class => 'm-l-15 waves-effect waves-light btn' do %>
              <i class="material-icons search-icon md-24">search</i>
            <% end %>
            <%= text_field_tag :query, nil, class: 'm-l-15 search-field' %>
          <% end if current_page?(products_path) || current_page?(root_path) %>
          <ul id="nav-mobile" class="right">
            <li>
              <a href="/products">Products
                <% if current_page?(products_path) || current_page?(root_path) %>
                  <span class="new badge" data-badge-caption='/ <%= Product.all.count %>' ><%= @products.count %></span>
                <% end %>
              </a>
            </li>
              <!-- Dropdown Trigger -->
              <li><a class="dropdown-trigger w-150" href="#!" data-target="dropdown">Account<i class="material-icons right">arrow_drop_down</i></a></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
<% end %>

<script type="text/javascript">
  var elems = document.querySelectorAll('.dropdown-trigger');
  var instances = M.Dropdown.init(elems, {coverTrigger: false, constrainWidth: true});
</script>